from db import get_connection
def add_product():
    # p_id=int(input("Enter product id:"))
    p_name=input("Enter product name:")
    p_price=input("Enter product price:")
    connection=get_connection()
    cur=connection.cursor()
    cur.execute("insert into product(name,price)values(%s,%s)",(p_name,p_price))
    connection.commit()
    connection.close()
    print("product added successfully")
def view_product():
    connection=get_connection()
    cur=connection.cursor()
    cur.execute("select * from product")
    data=cur.fetchall()
    # print(data)
    for i in data:
        print(i)
    connection.close()
    print("data fetched successfully")
def update_product():
    prod_id=int(input("Enter a product id which we want to update:"))
    product_name=input("enter product name:")
    product_price=input("enter product price:")
    connection=get_connection()
    cur=connection.cursor()
    cur.execute("update product set name=%s,price=%s where id=%s",(product_name,product_price,prod_id))
    connection.commit()
    connection.close()
    print("product is updated successfullly ")
def delete_product():
    prd_id=int(input("enetr a product which u want delete:"))
    connection=get_connection()
    cur=connection.cursor()
    cur.execute("delete from product where id=%s",(prd_id,))
    connection.commit()
    connection.close()
    print("product is deleted succesfully")